### ISSUE TITLE
Problém jednoznakového identifikátoru

### ISSUE THREAD

**Issue by vairad** [vairad/zcu-fjp#3]
Antlr neoznačí jako identifikátor jeden znak, byť by dle zápisu iterace měl.

**Comment by vairad** [comment]
Jde obecně o problém toho, že jeden znak to nesežere jako token... tzn:
`int ahoj = 5` je problém ale `int ahoj = 54` už rozloží do stromu.

**Comment by buzzcz** [comment]
Fixed by using 'fragment' in token specification of DigitSymbol and NoDigitSymbol
